### ISSUE TITLE
Greta says that we really should stop calling it the Brain, it should just be Atomist

### ISSUE THREAD

**Issue by russmiles** [atomisthq/lifecycle-demo#4]
See the title

**Comment by kipz** [comment]
+1

**Comment by russmiles** [comment]
We also should really put effort into making sure that the bot responds quickly...

**Comment by russmiles** [comment]
General comment: Unhappy smile/confused is really annoying from the Bot

**Comment by russmiles** [comment]
Sometimes there seems to be a long delay with no notice of what the Bot is doing, frequently during demos.
