### ISSUE TITLE
It should work, right? But it doesn't .... and I blame

### ISSUE THREAD

**Issue by russmiles** [atomisthq/lifecycle-demo#5]
It was definitely <@U0KUC2TPH>

**Comment by russmiles** [comment]
Hmm, maybe @Lawouach

**Comment by russmiles** [comment]
It was Christian instead ... actually, it was Siobhan.

**Comment by slimslenderslacks** [comment]
doing a demo with Brian right now

**Comment by cdupuis** [comment]
Is this really a bug.

**Comment by russmiles** [comment]
Why me? Or perhaps we should get a "Blame Russ" custom button in there ;)
